edge.tts.endpoint       = <your api endpoint>
edge.tts.api-key        = <your api key>
edge.tts.proxy.enabled  = true
edge.tts.proxy.server   = <your proxy server host>
edge.tts.proxy.port     = 8080
edge.tts.proxy.user     = <user name for proxy server>
edge.tts.proxy.password = <password the user for proxy server>